
# Legendary Tooltips Configuration Instructions
#
# *** READ THIS FIRST ***
#
# By default, this mod does not apply special borders to most items.  It was designed to work well with mod packs
# where the available selection of items can vary widely, so it is up to the user or mod pack designer to customize as needed.
# There are many options available for setting up which custom borders (also called frames) apply to which items.  Follow these steps:
#   1. Decide which items you want to have custom borders, and which borders.  Note that each custom border has a number associated with it (starting at 0).
#   2. For each custom border you want to use, fill out the associated list in the "definitions" section.  This will be filled out with a list of "selectors",
#      each of which tell the mod what items have that border.  Please read the information above the definitions section for specifics.
#   3. Selectors for borders are checked in the order provided in the "priorities" section.  Once a match is found, that border is displayed.
#      For example, if border 0 had the selector "%Diamond" and border 1 had the selector "diamond_sword", they would both match for diamond swords.
#      In this case, whichever border number came first in the priority list would be the border that would get drawn in-game.
#   4. Optionally, border colors associated with custom borders can be set in the "colors" section.  The start color is the color at the top of the tooltip,
#      and the end color is the bottom, with a smooth transition between.  Please read the information above the color section for specifics.
[client]

	[client.visual_options]
		# Whether item names in tooltips should have a line under them separating them from the rest of the tooltip.
		name_separator = true
		# If enabled, tooltip border colors will match item rarity colors (except for custom borders).
		borders_match_rarity = false
		# If enabled, tooltips will display a drop shadow.
		tooltip_shadow = false
		# If enabled, items showing a custom border will have a special shine effect when hovered over.
		shine_effect = true
		# If enabled, tooltip titles will be drawn centered.
		centered_title = false
		# If enabled, tooltips with custom borders will always be at least wide enough to display all border decorations.
		enforce_minimum_width = false

	# Entry types:
	#    Item name - Use item name for vanilla items or include mod name for modded items.  Examples: "minecraft:stick", "iron_ore"
	#    Tag - $ followed by tag name.  Examples: "$forge:stone", "$planks"
	#    Mod name - @ followed by mod identifier.  Examples: "@spoiledeggs"
	#    Rarity - ! followed by item's rarity.  This is ONLY vanilla rarities.  Examples: "!uncommon", "!rare", "!epic"
	#    Item name color - # followed by color hex code, the hex code must match exactly.  Examples: "#23F632"
	#    Display name - % followed by any text.  Will match any item with this text in its tooltip display name.  Examples: "%Netherite", "%[Uncommon]"
	#    Tooltip text - Will match any item with this text anywhere in the tooltip text (besides the name).  Examples: "^Legendary"
	#    NBT tag - & followed by tag name and optional comparator (=, >, <, or !=) and value, in the format <tag><comparator><value> or just <tag>.  Examples: "&Damage=0", "&Tier>1", "&map!=128", "&Enchantments"
	[client.definitions]
		level0_entries = ["!epic", "!rare", "!uncommon", "&Enchantments", "%UU-Matter", "%Final Broom"]
		level1_entries = ["^ender", "^Ender", "%ender", "%Ender", "%end gobber", "%End Gobber", "%End ", "%Adamantium"]
		level2_entries = ["%diamond", "^diamond", "%Diamond", "^Diamond", "$c:diamonds", "%platinum", "%Platinum", "^platinum", "^Platinum", "%sheldonite", "%Sheldonite", "^sheldonite", "^Sheldonite", "%mixed metal", "%Mixed Metal"]
		level3_entries = ["%gold", "^gold", "%Gold", "^Gold", "%yellow garnet", "%Yellow Garnet", "^yellow garnet", "^Yellow Garnet", "%phosphorous", "%Phosphorous", "%sulfur", "%Sulfur"]
		level4_entries = ["&energy", "^energy", "^Energy"]
		level5_entries = ["%redstone", "^redstone", "%Redstone", "^Redstone", "$c:redstone", "^ruby", "^Ruby", "%ruby", "%Ruby", "%red garnet", "%Red Garnet", "^red garnet", "^Red Garnet", "%pyrite", "%Pyrite", "%almandine", "%Almandine", "%spessartine", "%Spessartine", "%Mushroom", "%Nether Gobber"]
		level6_entries = ["^axolotl", "^Axolotl", "%axolotl", "%Axolotl", "%chromium", "%Chromium", "$candle_cakes"]
		level7_entries = ["$c:lava", "%lava", "%Lava", "%hot tungstensteel", "%Hot Tungstensteel", "%blaze", "%Blaze", "%magma", "%Magma"]
		level8_entries = ["$c:water", "%water", "%Water", "%aqua", "%Aqua"]
		level9_entries = ["^amethyst", "^Amethyst", "%amethyst", "%Amethyst", "%pyrope", "%Pyrope", "%obsidian", "%Obsidian", "%Superconductor", "%Vibranium", "%Coffin", "%Vampire"]
		level10_entries = ["%emerald", "%Emerald", "^peridot", "^Peridot", "%peridot", "%Peridot", "%olivine", "%Olivine", "%uvarovite", "%Uvarovite", "%sphalerite", "%Sphalerite"]
		level11_entries = ["%lapis", "%Lapis", "^sapphire", "^Sapphire", "%sapphire", "%Sapphire", "%lazurite", "%Lazurite", "%sodalite", "%Sodalite", "%Gobber"]
		level12_entries = ["^copper", "^Copper", "%copper", "%Copper", "%bauxite", "%Bauxite", "%brass", "%Brass", "%bronze", "%Bronze", "%electrum", "%Electrum", "%advanced alloy", "%Advanced Alloy", "%cinnabar", "%Cinnabar", "%andradite", "%Andradite", "%grossular", "%Grossular", "%calcite", "%Calcite", "%saltpeter", "%Saltpeter"]
		level13_entries = ["%coal", "%Coal", "^charcoal", "^Charcoal", "%charcoal", "%Charcoal", "^netherite", "^Netherite", "%netherite", "%Netherite", "%lead", "%Lead", "%flint", "%Flint", "%tungstensteel", "%Tungstensteel", "%basalt", "%Basalt", "%marble", "%Marble"]
		level14_entries = ["^Tin", "%Tin", "^iron", "^Iron", "%iron", "%Iron", "^aluminum", "^Aluminum", "%aluminum", "%Aluminum", "^quartz", "^Quartz", "%quartz", "%Quartz", "%galena", "%Galena", "%iridium", "%Iridium", "%silver", "%Silver", "%invar", "%Invar", "%nickel", "%Nickel", "%steel", "%Steel", "%titanium", "%Titanium", "%tungsten", "%Tungsten", "%zinc", "%Zinc", "%magnesium", "%Magnesium", "%manganese", "%Manganese", "%HV Cable"]
		level15_entries = []
		# Enter blacklist selectors here using the same format as above. Any items that match these selectors will NOT show a border.
		blacklist = []

	# Set border priorities here.  This should be a list of numbers that correspond to border levels, with numbers coming first being higher priority.  Optionally, -1 can be inserted to indicate relative priority of data and api-defined borders.  If you don't know what that means, don't worry about it.
	[client.priorities]
		priorities = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

	# The start and end border colors and background colors of each level.
	# Note that they can be entered as any one of: a decimal or hex color code in the format 0xAARRGGBB or 0xRRGGBB, OR a string color name or color code.
	# Examples: 0xFFFF00, 0xFF73D984, 4290445567, "red", "#FFCC00" are all valid.
	[client.colors]
		level0_start_color = 4288244002
		level0_end_color = 4284103197
		level0_bg_color = 4027976192
		level1_start_color = "#349989"
		level1_end_color = "#03261F"
		level1_bg_color = 4027976192
		level2_start_color = "#8DF3E3"
		level2_end_color = "#209582"
		level2_bg_color = 4027976192
		level3_start_color = "#FDF55F"
		level3_end_color = "#d6ce38"
		level3_bg_color = 4027976192
		level4_start_color = "#d69f38"
		level4_end_color = "#387fd6"
		level4_bg_color = 4027976192
		level5_start_color = "#FB0000"
		level5_end_color = "#710000"
		level5_bg_color = 4027976192
		level6_start_color = "#FBC1E3"
		level6_end_color = "#C8629E"
		level6_bg_color = 4027976192
		level7_start_color = "#b05625"
		level7_end_color = "#ffcf7d"
		level7_bg_color = 4027976192
		level8_start_color = "#64ade8"
		level8_end_color = "#255ab0"
		level8_bg_color = 4027976192
		level9_start_color = "#B38EF3"
		level9_end_color = "#54398A"
		level9_bg_color = 4027976192
		level10_start_color = "#17DD62"
		level10_end_color = "#009529"
		level10_bg_color = 4027976192
		level11_start_color = "#466ED2"
		level11_end_color = "#0A2B7B"
		level11_bg_color = 4027976192
		level12_start_color = "#E77C56"
		level12_end_color = "#C15A36"
		level12_bg_color = 4027976192
		level13_start_color = "#323232"
		level13_end_color = "#252525"
		level13_bg_color = 4027976192
		level14_start_color = "#D8D8D8"
		level14_end_color = "#727272"
		level14_bg_color = 4027976192
		level15_start_color = "#FF0000"
		level15_end_color = "#0000FF"
		level15_bg_color = 4027976192

